########################################################
import unittest
from modules.metadata import metadata
from modules.sentiment_analysis import sentiment_analysis

class TestSentimentAnalysis(unittest.TestCase):
    def test_sentiment_analysis(self):
        #test 1
        #testing the alice_smith_cat_story.docx
        input_data = metadata({"doc": "tests/Alice_Smith_Cat_Story.docx"})
        result = sentiment_analysis(input_data)
        expected_result = {'metadata': {'author': 'Alice Smith', 'category': 'Story', 'comments': 'This is a story about a curious cat named Mittens.', 'content_status': 'Draft', 'created': '2013-12-23T23:15:00', 'identifier': '12345678-1234-1234-1234-123456789012', 'keywords': 'cat, story, adventure', 'language': 'en-US', 'last_modified_by': 'Alice Smith', 'last_printed': None, 'modified': '2013-12-23T23:15:00', 'revision': 1, 'subject': "A Cat's Adventure", 'title': 'fluttering butterfly outside the window.', 'version': '1.0', 'name': 'tests/Alice_Smith_Cat_Story.docx', 'paragraphs': ["Alice Smith's Cat", 'In a cozy little house nestled amidst the bustling city, lived a ginger cat named Mittens, the beloved companion of Alice Smith. She was known for her playful antics and insatiable curiosity. One sunny afternoon, while basking in a patch of warm sunlight, Mittens spotted a fluttering butterfly outside the window. She leaped off the window sill, tail swishing excitedly, and darted towards the fluttering wings. Mittens pounced and batted at the butterfly with her paws, but the nimble creature fluttered away, leaving her wanting more. Undeterred, Mittens continued to explore the house, searching for new adventures.'], 'text': "Alice Smith's Cat In a cozy little house nestled amidst the bustling city, lived a ginger cat named Mittens, the beloved companion of Alice Smith. She was known for her playful antics and insatiable curiosity. One sunny afternoon, while basking in a patch of warm sunlight, Mittens spotted a fluttering butterfly outside the window. She leaped off the window sill, tail swishing excitedly, and darted towards the fluttering wings. Mittens pounced and batted at the butterfly with her paws, but the nimble creature fluttered away, leaving her wanting more. Undeterred, Mittens continued to explore the house, searching for new adventures."}, 'sentiment_scores': {'neg': 0.0, 'neu': 0.876, 'pos': 0.124, 'compound': 0.8658}}
        self.assertEqual(result, expected_result)

        #test 2
        #testing the Bob_Johnson_Kitten_Story.docx
        input_data = metadata({"doc": "tests/Bob_Johnson_Kitten_Story.docx"})
        result = sentiment_analysis(input_data)
        expected_result =  {'metadata': {'author': 'Bob Johnson', 'category': 'Animals', 'comments': 'This is a story about a mischievous kitten.', 'content_status': 'Draft', 'created': '2013-12-23T23:15:00', 'identifier': '98765432-1234-1234-1234-123456789012', 'keywords': 'cat, kitten, mischievous', 'language': 'en-US', 'last_modified_by': 'Bob Johnson', 'last_printed': None, 'modified': '2013-12-23T23:15:00', 'revision': 1, 'subject': "A Kitten's Antics", 'title': "Bob Johnson's Kitten", 'version': '1.0', 'name': 'tests/Bob_Johnson_Kitten_Story.docx', 'paragraphs': ["Bob Johnson's Kitten", "In a quaint farmhouse surrounded by rolling hills, lived a fluffy white kitten named Snowball, the playful companion of Bob Johnson. He was known for his insatiable curiosity and mischievous energy. One crisp autumn morning, while chasing a dust bunny across the living room floor, Snowball stumbled upon a ball of yarn left unattended. Entranced by the colorful strands, he pounced and batted at the yarn, unraveling it in a frenzy. He chased the loose yarn around the room, leaving a trail of tangled threads in his wake. Bob chuckled as he watched the kitten's playful chaos, knowing he would need to gather the yarn before it became another casualty of Snowball's adventures."], 'text': "Bob Johnson's Kitten In a quaint farmhouse surrounded by rolling hills, lived a fluffy white kitten named Snowball, the playful companion of Bob Johnson. He was known for his insatiable curiosity and mischievous energy. One crisp autumn morning, while chasing a dust bunny across the living room floor, Snowball stumbled upon a ball of yarn left unattended. Entranced by the colorful strands, he pounced and batted at the yarn, unraveling it in a frenzy. He chased the loose yarn around the room, leaving a trail of tangled threads in his wake. Bob chuckled as he watched the kitten's playful chaos, knowing he would need to gather the yarn before it became another casualty of Snowball's adventures."}, 'sentiment_scores': {'neg': 0.093, 'neu': 0.807, 'pos': 0.1, 'compound': -0.0516}}
        self.assertEqual(result, expected_result)

        #test 3
        #testing the Charlie_Brown_Cat.docx
        input_data = metadata({"doc": "tests/Charlie_Brown_Cat.docx"})
        result = sentiment_analysis(input_data)
        expected_result =  {'metadata': {'author': 'Charlie Brown', 'category': 'Fiction', 'comments': 'This is a story about a brave cat on a journey.', 'content_status': 'Draft', 'created': '2013-12-23T23:15:00', 'identifier': '11223344-1234-1234-1234-123456789012', 'keywords': 'cat, journey, brave', 'language': 'en-US', 'last_modified_by': 'Charlie Brown', 'last_printed': None, 'modified': '2013-12-23T23:15:00', 'revision': 1, 'subject': "The Cat's Quest", 'title': "Charlie Brown's Cat", 'version': '1.0', 'name': 'tests/Charlie_Brown_Cat.docx', 'paragraphs': ["Charlie Brown's Cat", 'In a charming little bookstore nestled down a quiet street, lived a sleek black cat named Midnight, the loyal companion of Charlie Brown. He was known for his quiet nature and adventurous spirit. One rainy afternoon, while exploring the city streets, Midnight stumbled upon an old map tucked away in a corner. The map depicted a mysterious island rumored to hold great treasures. Intrigued by the possibility of adventure, Midnight embarked on a perilous journey across stormy seas and treacherous terrain, facing danger and challenges at every turn. But with courage and determination, Midnight pressed on, guided by the promise of discovery and the hope of returning home a hero.'], 'text': "Charlie Brown's Cat In a charming little bookstore nestled down a quiet street, lived a sleek black cat named Midnight, the loyal companion of Charlie Brown. He was known for his quiet nature and adventurous spirit. One rainy afternoon, while exploring the city streets, Midnight stumbled upon an old map tucked away in a corner. The map depicted a mysterious island rumored to hold great treasures. Intrigued by the possibility of adventure, Midnight embarked on a perilous journey across stormy seas and treacherous terrain, facing danger and challenges at every turn. But with courage and determination, Midnight pressed on, guided by the promise of discovery and the hope of returning home a hero."}, 'sentiment_scores': {'neg': 0.026, 'neu': 0.707, 'pos': 0.267, 'compound': 0.9817}}
        self.assertEqual(result, expected_result)

        #test 4
        #testing the Jane_Doe_Cat_Story.docx
        input_data = metadata({"doc": "tests/Jane_Doe_Cat_Story.docx"})
        result = sentiment_analysis(input_data)
        expected_result =  {'metadata': {'author': 'Jane Doe', 'category': 'Story', 'comments': 'This is a story about a pampered cat.', 'content_status': 'Draft', 'created': '2013-12-23T23:15:00', 'identifier': '55555555-1234-1234-1234-123456789012', 'keywords': 'cat, pampered, story', 'language': 'en-US', 'last_modified_by': 'Jane Doe', 'last_printed': None, 'modified': '2013-12-23T23:15:00', 'revision': 1, 'subject': 'A Pampered Life', 'title': "Jane Doe's Cat", 'version': '1.0', 'name': 'tests/Jane_Doe_Cat_Story.docx', 'paragraphs': ["Jane Doe's Cat", 'In a luxurious apartment overlooking the bustling city, lived a Persian cat named Duchess, the prized possession of Jane Doe. She was known for her regal demeanor and sophisticated taste. Every morning, Duchess would be awakened by the gentle clinking of her silver food dish, filled with gourmet cat food. After a leisurely breakfast, she would spend her days lounging on plush cushions, basking in sunbeams, and occasionally batting at feather toys presented by her devoted owner. One afternoon, while perched on a window sill, Duchess observed a stray cat navigating the alleyway below. The stray, thin and scruffy, rummaged through a bin, searching for scraps. Duchess watched with a mixture of curiosity and disdain, her pampered life a stark contrast to the struggles of the alley cat.'], 'text': "Jane Doe's Cat In a luxurious apartment overlooking the bustling city, lived a Persian cat named Duchess, the prized possession of Jane Doe. She was known for her regal demeanor and sophisticated taste. Every morning, Duchess would be awakened by the gentle clinking of her silver food dish, filled with gourmet cat food. After a leisurely breakfast, she would spend her days lounging on plush cushions, basking in sunbeams, and occasionally batting at feather toys presented by her devoted owner. One afternoon, while perched on a window sill, Duchess observed a stray cat navigating the alleyway below. The stray, thin and scruffy, rummaged through a bin, searching for scraps. Duchess watched with a mixture of curiosity and disdain, her pampered life a stark contrast to the struggles of the alley cat."}, 'sentiment_scores': {'neg': 0.041, 'neu': 0.865, 'pos': 0.093, 'compound': 0.7906}}
        self.assertEqual(result, expected_result)
        
        #test 5
        #testing the test_document5.docx  (an empty document)
        input_data = metadata({"doc": "tests/test_document5.docx"})
        result = sentiment_analysis(input_data)
        expected_result =  {'metadata': {'author': '', 'category': '', 'comments': '', 'content_status': '', 'created': '2013-12-23T23:15:00', 'identifier': '', 'keywords': '', 'language': '', 'last_modified_by': '', 'last_printed': None, 'modified': '2013-12-23T23:15:00', 'revision': 1, 'subject': '', 'title': '', 'version': '', 'name': 'tests/test_document5.docx', 'paragraphs': [], 'text': ''}, 'sentiment_scores': {'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound': 0.0}}
        self.assertEqual(result, expected_result)

        #test 6
        #testing null
        input_data = metadata({"doc": None})
        result = sentiment_analysis(input_data)
        expected_result =  {'metadata': {'author': 'python-docx', 'category': '', 'comments': 'generated by python-docx', 'content_status': '', 'created': '2013-12-23T23:15:00', 'identifier': '', 'keywords': '', 'language': '', 'last_modified_by': '', 'last_printed': None, 'modified': '2013-12-23T23:15:00', 'revision': 1, 'subject': '', 'title': '', 'version': '', 'name': None, 'paragraphs': [], 'text': ''}, 'sentiment_scores': {'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound': 0.0}}
        self.assertEqual(result, expected_result)





if __name__ == "__main__":
    unittest.main()